<?php

/**
 * @file
 * User time on site module.
 */

/**
 * Implements hook_entity_info().
 */
function user_time_on_site_entity_info() {
  return [
    'user_time_on_site' => [
      'label' => t('Active User Session'),
      'plural label' => t('Active User Sessions'),
      'entity class' => 'Entity',
      'controller class' => 'EntityAPIController',
      'base table' => 'user_time_on_site',
      'entity keys' => [
        'id' => 'id',
      ],
      'label callback' => 'entity_class_label',
      'uri callback' => 'entity_class_uri',
      'module' => 'user_time_on_site',
      'views controller class' => 'UserTimeOnSiteViewsController',
    ],
  ];
}

/**
 * Implements hook_exit().
 */
function user_time_on_site_exit() {
  global $user;
  // Anonymous user sessions aren't recorded.
  if (!$user->uid) {
    return;
  }
  // Update entity for current session, if found.
  $query = new EntityFieldQuery();
  $result = $query->entityCondition('entity_type', 'user_time_on_site')
    ->propertyCondition('uid', $user->uid)
    ->propertyCondition('last_time', time() - (15 * 60), '>=')
    ->execute();
  if (count($result)) {
    // Update current session.
    // db_update returns number of modified rows, but it can't be used to test
    // for existing session. For AJAX requests sent on page load and similar
    // requests in the same second, db_update shouldn't change the database.
    // It's least complicated to sometimes make a redundant UPDATE query.
    $updated = db_update('user_time_on_site')
      ->fields([
        'last_time' => time(),
      ])
      ->condition('uid', $user->uid)
      ->condition('last_time', time() - (15 * 60), '>=')
      ->execute();
  }
  else {
    // Insert new.
    db_insert('user_time_on_site')
      ->fields([
        'first_time' => time(),
        'last_time' => time(),
        'uid' => $user->uid,
      ])
      ->execute();
  }
}

/**
 * User time on site viewsController class.
 */
class UserTimeOnSiteViewsController extends EntityDefaultViewsController {

  /**
   * Treat dates as dates and relate user ID to user entity.
   */
  public function views_data() {
    $data = parent::views_data();
    $data['user_time_on_site']['first_time']['field']['handler'] = 'views_handler_field_date';
    $data['user_time_on_site']['last_time']['field']['handler'] = 'views_handler_field_date';
    $data['user_time_on_site']['uid'] = [
      'title' => t('User'),
      'relationship' => [
        'base' => 'users',
        'base field' => 'uid',
        'field' => 'uid',
        'handler' => 'views_handler_relationship',
        'label' => t('user'),
      ],
    ];
    return $data;
  }

}
